import type { Metadata } from "next";
import localFont from "next/font/local";
import HttpProvider from "./_frontend/providers/HttpProvider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HttpProvider>
          <div
            className="min-h-screen bg-no-repeat bg-cover  text-gray-900 flex justify-center "
            style={{
              backgroundImage: "url('/images/bg.webp')",
            }}
          >
            <div className="absolute inset-0 bg-black opacity-50"></div>

            <div className="h-fit lg:h-auto  relative max-w-screen-xl m-4 sm:m-10   shadow  rounded-lg flex justify-center flex-1 bg-dark-card  ">
              {children}
            </div>
          </div>
        </HttpProvider>
      </body>
    </html>
  );
}
