import TopLoader from "@/_frontend/components/loaders/TopLoader";
import GlobalModal from "@/_frontend/components/modals/GlobalModal";
import HttpProvider from "@/_frontend/providers/HttpProvider";
import { JotaiProvider } from "@/_frontend/providers/JotaiProvider";
import { cn } from "@/_frontend/utils/css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { inter, lexendDeca } from "./font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(inter.variable, lexendDeca.variable)}
        suppressHydrationWarning
      >
        <HttpProvider>
          <TopLoader />
          <JotaiProvider>
            {children}
            <Toaster />
            <GlobalModal />
          </JotaiProvider>
        </HttpProvider>
      </body>
    </html>
  );
}
